### PR TITLE
Feature/96 updated client library

### LINKED ISSUE #96: Update Verida libraries
Update Verida libraries to v1.1.4 to support new schemas

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Updated verida libraries to the latest version

```
   "@verida/account-web-vault": "^1.1.5",
    "@verida/client-ts": "^1.1.6",
```

resolves #96

### CODE REVIEW

**Comment by nick-verida** [comment]
When I run this I get 

```
./node_modules/did-jwt/lib/index.module.js 1684:17
Module parse failed: Unexpected token (1684:17)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|               // TODO: should be able to use non base58 keys too
|               return key.type === 'X25519KeyAgreementKey2019' && Boolean(key.publicKeyBase58);
>             })) ?? [];
|             if (!pks.length && !controllerEncrypters.length) throw new Error(`no_suitable_keys: Could not find x25519 key for ${did}`);
|             return pks.map(pk => x25519Encrypter(base58ToBytes(pk.publicKeyBase58), pk.id)).concat(...controllerEncrypters);
```

I believe this is the same issue you discussed on Slack over the weekend. Not sure what the fix was there?

**Comment by tahpot** [comment]
@nick-verida @cmcWebCode40 Update to the latest `npm`.

**Comment by cmcWebCode40** [comment]
- updated verida packages 

```    
   "@verida/account-web-vault": "^1.1.6",
    "@verida/client-ts": "^1.1.8",
```

- Updated user profile avatar 

- Updated schema URL

 #96

**Review by nick-verida — COMMENTED** [review]
looks good. Merging

**Pull request merged**
