### PR TITLE
Feature/107 error in markdown

### PR DESCRIPTION
**Pull request by cmcWebCode40**
@nick-verida,

I have resolved this issue, had to move the event-listeners in the app.js file, which listens for events in the  react-app  globally, and I think that's where the login throws  the above [here](https://github.com/verida/markdown-notes-demo/issues/107) and I also refactor the service API  methods, 

- `initNotesEventLister()` 
- `initProfileEventLister()` 
 

see commit in my PR

### CODE REVIEW

**Comment by nick-verida** [comment]
After:

```
rm -rf markdown-notes-demo
cd markdown-notes-demo
git checkout feature/107-error-in-markdown
yarn
yarn start
```

I get this:

image

**Review by nick-verida — CHANGES_REQUESTED** [review]
See comment

**Comment by cmcWebCode40** [comment]
@nick-verida , i have modified the `routeguard` issue above

**Review by nick-verida — CHANGES_REQUESTED** [review]
See comment

**Comment by nick-verida** [comment]
image

Steps to replicate:
* Login (with an existing account)

This was an error you had previously where you were assuming people always had some notes but it can in fact be null.

**Review by nick-verida — APPROVED** [review]
Seems to work now. Merging and deploying

**Pull request merged**
